[tools]
"aqua:evilmartians/lefthook" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:jessfraz/dockfmt" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:tamasfe/taplo" = "latest"
"aqua:zricethezav/gitleaks" = "latest"
"npm:markdownlint-cli2" = "latest"
"pipx:gitfluff" = "latest"
"pipx:yamllint" = "latest"
prettier = "latest"
python = "3.12"
shfmt = "latest"
task = "3"
uv = "latest"
